# ==========================================
# THIS FILE IS AUTO-GENERATED BY A SCRIPT.
# DO NOT EDIT THIS FILE MANUALLY.
# Run tools/generate_ui_ghosts.py to update.
# ==========================================

from __future__ import annotations
from .elements import Button, Slot, TextBox
from .wrappers import BorderWrapper, FlashWrapper, ShadowWrapper

# --- Matrix Combinations ---
class BorderButton(BorderWrapper, Button): pass
class BorderSlot(BorderWrapper, Slot): pass
class BorderTextBox(BorderWrapper, TextBox): pass
class FlashButton(FlashWrapper, Button): pass
class FlashSlot(FlashWrapper, Slot): pass
class FlashTextBox(FlashWrapper, TextBox): pass
class ShadowButton(ShadowWrapper, Button): pass
class ShadowSlot(ShadowWrapper, Slot): pass
class ShadowTextBox(ShadowWrapper, TextBox): pass

# --- Explicit Exports for Wildcard Import Support ---
__all__ = ["BorderButton", "BorderSlot", "BorderTextBox", "FlashButton", "FlashSlot", "FlashTextBox", "ShadowButton", "ShadowSlot", "ShadowTextBox"]
