classDiagram
  class src {
  }
  class core {
  }
  class assets {
  }
  class asset_data {
  }
  class asset_loader {
  }
  class base {
  }
  class collections {
  }
  class database {
  }
  class entities {
  }
  class world {
  }
  class controls {
  }
  class database {
  }
  class debug_logger {
  }
  class spritesheet {
  }
  class states {
  }
  class base {
  }
  class hud {
  }
  class menus {
  }
  class playing {
  }
  class types {
  }
  class data_models {
  }
  class enums {
  }
  class generated_enums {
  }
  class geometry {
  }
  class ui_utils {
  }
  class custom_types {
  }
  class entities {
  }
  class animal {
  }
  class components {
  }
  class animation {
  }
  class interaction {
  }
  class inventoryComponent {
  }
  class entity {
  }
  class items {
  }
  class plant {
  }
  class player {
  }
  class groups {
  }
  class camera {
  }
  class plant_group {
  }
  class ui_group {
  }
  class settings {
  }
  class ui {
  }
  class InventoryUI {
  }
  class timer {
  }
  class ui_elements {
  }
  class ui_factory {
  }
  class ui_ghosts {
  }
  class wrappers {
  }
  class world {
  }
  class level {
  }
  class tile {
  }
  core --> controls
  core --> database
  core --> debug_logger
  core --> spritesheet
  core --> ui_utils
  assets --> asset_loader
  assets --> base
  assets --> collections
  assets --> entities
  assets --> world
  assets --> database
  asset_data --> types
  asset_data --> settings
  asset_loader --> core
  asset_loader --> asset_data
  asset_loader --> base
  asset_loader --> collections
  asset_loader --> database
  asset_loader --> entities
  asset_loader --> world
  asset_loader --> types
  base --> core
  collections --> core
  collections --> asset_data
  collections --> base
  collections --> types
  database --> core
  database --> base
  database --> types
  entities --> core
  entities --> asset_data
  entities --> base
  entities --> types
  world --> core
  world --> asset_data
  world --> base
  world --> types
  world --> settings
  controls --> debug_logger
  controls --> types
  database --> types
  debug_logger --> settings
  spritesheet --> core
  spritesheet --> assets
  states --> base
  states --> hud
  states --> menus
  states --> playing
  base --> assets
  base --> types
  base --> groups
  base --> settings
  base --> ui
  hud --> core
  hud --> assets
  hud --> base
  hud --> types
  hud --> settings
  hud --> ui
  menus --> core
  menus --> base
  menus --> types
  menus --> settings
  menus --> ui
  playing --> assets
  playing --> base
  playing --> hud
  playing --> types
  playing --> entities
  playing --> groups
  playing --> settings
  playing --> level
  types --> data_models
  types --> enums
  types --> generated_enums
  types --> geometry
  data_models --> assets
  data_models --> enums
  data_models --> geometry
  geometry --> enums
  ui_utils --> core
  custom_types --> types
  custom_types --> entity
  custom_types --> InventoryUI
  custom_types --> tile
  entities --> animal
  entities --> entity
  entities --> items
  entities --> plant
  entities --> player
  components --> animation
  components --> interaction
  components --> inventoryComponent
  animation --> assets
  animation --> types
  interaction --> core
  interaction --> controls
  inventoryComponent --> core
  inventoryComponent --> controls
  inventoryComponent --> settings
  inventoryComponent --> ui
  inventoryComponent --> InventoryUI
  entity --> types
  entity --> settings
  items --> core
  items --> assets
  items --> types
  items --> tile
  plant --> core
  plant --> assets
  plant --> types
  plant --> entity
  plant --> settings
  player --> core
  player --> controls
  player --> types
  player --> entities
  player --> components
  player --> entity
  player --> groups
  player --> settings
  player --> tile
  groups --> camera
  groups --> plant_group
  groups --> ui_group
  camera --> settings
  plant_group --> entities
  ui --> InventoryUI
  ui --> timer
  ui --> ui_elements
  ui --> ui_factory
  ui --> ui_ghosts
  ui --> wrappers
  InventoryUI --> core
  InventoryUI --> items
  InventoryUI --> settings
  InventoryUI --> ui_elements
  InventoryUI --> ui_factory
  InventoryUI --> wrappers
  ui_elements --> core
  ui_elements --> assets
  ui_factory --> core
  ui_factory --> assets
  ui_factory --> ui
  ui_factory --> InventoryUI
  ui_factory --> ui_elements
  ui_factory --> wrappers
  ui_ghosts --> ui_elements
  ui_ghosts --> wrappers
  wrappers --> assets
  wrappers --> timer
  world --> level
  world --> tile
  level --> core
  level --> assets
  level --> plant
  level --> settings
  level --> tile
  tile --> assets
  tile --> asset_data
  tile --> settings
  asset_loader ..> custom_types
  base ..> assets
  base ..> custom_types
  collections ..> assets
  collections ..> custom_types
  database ..> assets
  entities ..> custom_types
  world ..> assets
  database ..> custom_types
  base ..> custom_types
  hud ..> custom_types
  menus ..> custom_types
  playing ..> custom_types
  data_models ..> states
  data_models ..> custom_types
  custom_types ..> states
  custom_types ..> entities
  custom_types ..> components
  custom_types ..> groups
  custom_types ..> ui
  custom_types ..> world
  animation ..> custom_types
  interaction ..> custom_types
  inventoryComponent ..> custom_types
  entity ..> custom_types
  entity ..> entities
  items ..> custom_types
  items ..> entities
  items ..> groups
  plant ..> custom_types
  plant ..> items
  plant ..> player
  player ..> custom_types
  camera ..> entities
  plant_group ..> custom_types
  ui_group ..> custom_types
  InventoryUI ..> custom_types
  ui_elements ..> custom_types
  ui_factory ..> custom_types
  wrappers ..> custom_types
  wrappers ..> ui
  level ..> custom_types
  tile ..> custom_types
