import os
import sys
import subprocess
from src.core.debug_logger import Log

class BaseScriptGenerator:
    """Shared base architecture for tools that compile and generate source files."""
    
    def __init__(self, output_path: str) -> None:
        self.output_path = output_path

    def _prepare_directory(self) -> None:
        """Ensures the nested target asset directories exist safely before writing."""
        os.makedirs(os.path.dirname(self.output_path), exist_ok=True)

    def _get_autogen_header(self, script_filename: str) -> str:
        """Generates the standardized terminal-style warning header for generated assets."""
        return (
            "# ==========================================\n"
            "# THIS FILE IS AUTO-GENERATED BY A SCRIPT.\n"
            "# DO NOT EDIT THIS FILE MANUALLY.\n"
            f"# Run tools/{script_filename} to update.\n"
            "# ==========================================\n\n"
        )
        
    def write_if_changed(self, body_content: str, script_filename: str) -> bool:
        """
        Appends the autogen header, checks if the compilation introduces fresh data, 
        and updates the disk only if modification diffs are identified.
        Returns True if a file write occurred, False if skipped.
        """
        full_compiled_text = self._get_autogen_header(script_filename) + body_content
        self._prepare_directory()

        # SMART CACHING CHECK: Compare existing string contents against new compilation buffer
        if os.path.exists(self.output_path):
            with open(self.output_path, "r", encoding="utf-8") as f:
                if f.read() == full_compiled_text:
                    Log.info(f"No adjustments detected for '{self.output_path}'. Skipping file write.")
                    return False

        # If mismatch detected, commit adjustments to the filesystem
        with open(self.output_path, "w", encoding="utf-8") as f:
            f.write(full_compiled_text)
            
        Log.info(f"Baked updates to '{self.output_path}'.")
        return True
    

    @staticmethod
    def generate_all(tools_dir: str = "tools") -> None:
        """Scans the specified directory for 'generate_*.py' scripts and executes them sequentially."""
        if not os.path.exists(tools_dir):
            Log.error(f"Error: Tools directory '{tools_dir}' does not exist.")
            return

        Log.info(f"Master Build Started: Scanning '{tools_dir}' for generation pipelines...\n")
        
        # Gather all files that fit your script-generated naming scheme
        scripts = [
            f for f in os.listdir(tools_dir) 
            if f.startswith("generate_") and f.endswith(".py")
        ]
        
        if not scripts:
            Log.info("No generation scripts found.")
            return

        # Sort alphabetically so they run in a predictable sequence
        scripts.sort()
        
        for script in scripts:
            script_path = os.path.join(tools_dir, script)
            Log.info(f"-> Launching: {script}")
            ("-" * 40)
            
            # Run the file using the exact same python execution environment
            result = subprocess.run([sys.executable, script_path])
            Log.divider(40)
            if result.returncode == 0:
                Log.success(f"-> Completed: {script} Successfully.\n")
            else:
                Log.error(f"-> WARNING: {script} exited with error code {result.returncode}.\n")

        Log.success("Master Build Pipeline finished completely.")
        
if __name__ == "__main__":
    # Tells the engine to look inside the "tools" folder and execute everything
    BaseScriptGenerator.generate_all(tools_dir="tools")