import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from src.utils import Log

from .project_environment import ProjectEnv


class BaseScriptGenerator:
    """Shared base architecture for tools that compile and generate source files."""
    
    def __init__(self, output_rel_path: str | Path) -> None:
        # We safely resolve all generated files relative to the ROOT_DIR
        self.output_path: Path = ProjectEnv.ROOT_DIR / output_rel_path

    def _prepare_directory(self) -> None:
        """Ensures the nested target asset directories exist safely before writing."""
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        
    def _get_autogen_header(self, script_filename: str) -> str:
        """Generates the standardized terminal-style warning header with a timestamp."""
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d at %H:%M:%S")
        return (
            "# ==========================================\n"
            "# THIS FILE IS AUTO-GENERATED BY A SCRIPT.\n"
            "# DO NOT EDIT THIS FILE MANUALLY.\n"
            f"# Run tools/{script_filename} to update.\n"
            f"# Generated on: {timestamp}\n"
            "# ==========================================\n\n"
        )
        
    def write_if_changed(self, body_content: str, script_filename: str) -> bool:
        """ Appends the autogen header, checks if the compilation introduces fresh data, 
        and updates the disk only if modification diffs are identified.
        Returns True if a file write occurred, False if skipped."""
        full_compiled_text = self._get_autogen_header(script_filename) + body_content
        self._prepare_directory()

        # SMART CACHING CHECK: Compare existing string contents against new compilation buffer
        if self.output_path.exists() and self.output_path.read_text(encoding="utf-8") == full_compiled_text:
            Log.info(f"No adjustments detected for '{self.output_path.name}'. Skipping file write.")
            return False

        # If mismatch detected, commit adjustments to the filesystem
        self.output_path.write_text(full_compiled_text, encoding="utf-8")
        Log.info(f"Baked updates to '{self.output_path.name}'.")
        return True
    
    def write_timestamp_log(self, log_rel_path: str | Path, label: str = "Asset") -> None:
        """Writes a standardized timestamp log file for any generator tool."""
        log_path = ProjectEnv.ROOT_DIR / log_rel_path
        log_path.parent.mkdir(parents=True, exist_ok=True)
        
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d at %H:%M:%S")
        log_path.write_text(f"{label} last updated on: {now}\n", encoding="utf-8")
        Log.info(f"Timestamp log recorded: {log_path.relative_to(ProjectEnv.ROOT_DIR)}")

    @staticmethod
    def generate_all(tools_dir: str = "tools") -> None:
        """Scans the specified directory for 'generate_*.py' scripts and executes them sequentially."""
        Log.info(f"Master Build Started: Scanning '{ProjectEnv.TOOLS_DIR.name}' for generation pipelines...\n")
        
        # Gather all valid generation scripts
        scripts = sorted(
            f for f in ProjectEnv.TOOLS_DIR.iterdir() 
            if f.is_file() and f.name.startswith("generate_") and f.name.endswith(".py")
        )
        
        if not scripts:
            Log.info("No generation scripts found.")
            return

        # Sort alphabetically so they run in a predictable sequence
        scripts.sort()
        
        for script in scripts:
            Log.info(f"-> Launching: {script}")
            Log.divider(40)
            
            # Run the file using the exact same python execution environment
            result = subprocess.run([sys.executable, str(script)], check=False)
            Log.divider(40)
            if result.returncode == 0:
                Log.success(f"-> Completed: {script} Successfully.\n")
            else:
                Log.error(f"-> WARNING: {script} exited with error code {result.returncode}.\n")

        Log.success("Master Build Pipeline finished completely.")
        
if __name__ == "__main__":
    # Tells the engine to look inside the "tools" folder and execute everything
    BaseScriptGenerator.generate_all(tools_dir="tools")