import sqlite3
import os
import re
from dataclasses import dataclass # <-- Import this!

@dataclass
class EnumDefinition:
    """A structured container for everything needed to build an Enum class."""
    class_name: str
    keys: list[str]
    docstring: str

# --- Path Configuration ---
# Using os.path.join to ensure this works on both Windows and Mac
DB_PATH = os.path.join("Assets", "data", "gamedata.db")
OUTPUT_PATH = os.path.join("core", "types", "generated_enums.py")

# New paths for your asset folders
PLAYER_ASSETS_PATH = os.path.join("Assets", "Player")
ANIMAL_ASSETS_PATH = os.path.join("Assets", "Farm_Animals")

def camel_to_screaming_snake(name: str) -> str:
    """Converts 'BlueBird' to 'BLUE_BIRD' for the Enum variable name."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).upper()

def write_enum_class(file_obj, enum_def: EnumDefinition) -> None:
    """Helper to write an Enum class to the generated file using a dataclass."""
    # The function can handle its own safety check now!
    if not enum_def.keys: 
        return 
    
    file_obj.write(f"class {enum_def.class_name}(str, Enum):\n")
    
    if enum_def.docstring:
        file_obj.write(f'    """{enum_def.docstring}"""\n')
        
    for key in enum_def.keys:
        if " " in key:
            var_name = key.replace(" ", "_").upper()
        else:
            var_name = camel_to_screaming_snake(key)
            
        file_obj.write(f'    {var_name} = "{key}"\n')
        
    file_obj.write("\n")

def fetch_keys_from_table(cursor: sqlite3.Cursor, table_name: str) -> EnumDefinition:
    """Fetches IDs from a database table and generates an automatic docstring."""
    cursor.execute(f"SELECT id FROM {table_name}")
    keys = [row[0] for row in cursor.fetchall()]
    
    # Auto-generate the docstring based on the table name
    docstring = f"Maps directly to the '{table_name}' table in the gamedata database."
    
    # 2. Generate Class Name (e.g., 'items' -> 'ItemID')
    base_name = table_name.capitalize()
    if base_name.endswith("s"):
        base_name = base_name[:-1] # Remove the plural 's'
    class_name = f"{base_name}ID"
    
    return EnumDefinition(
        class_name=class_name,
        keys=keys,
        docstring=docstring
    )

def scan_directory_for_names(directory_path: str) -> EnumDefinition|None:
    """Scans a directory for filenames, generating the keys, docstring, and Class Name."""
    if not os.path.exists(directory_path):
        print(f"Warning: Could not find directory at {directory_path}")
        return None
        
    names = []
    for item in os.listdir(directory_path):
        if item.startswith("."): 
            continue
        name, _ = os.path.splitext(item)
        if name not in names:
            names.append(name)
            
    folder_name = os.path.basename(directory_path)
    
    # 1. Generate Docstring
    docstring = f"Maps directly to the filenames in the '{folder_name}' directory."
    
    # 2. Generate Class Name (e.g., 'Farm_Animals' -> 'FarmAnimalType')
    # Replace underscores with spaces, capitalize each word, then remove spaces
    clean_name = folder_name.replace("_", " ").title().replace(" ", "")
    if clean_name.endswith("s"):
        clean_name = clean_name[:-1] # Remove the plural 's'

    return EnumDefinition(
        class_name=f"{clean_name}Type",
        keys=sorted(names),
        docstring=docstring
    )

def build_enum_file():
    print(f"Connecting to database at: {DB_PATH}...")
    enums_to_build = []
    # Fetch from Database
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        
        enums_to_build.append(fetch_keys_from_table(cursor, "items"))
        enums_to_build.append(fetch_keys_from_table(cursor, "shops"))

        conn.close()
    except sqlite3.OperationalError as e:
        print(f"Database Error: {e}")
        print("Make sure your table and column names match the SQL queries!")
        return

    # Fetch from Folders
    enums_to_build.append(scan_directory_for_names(PLAYER_ASSETS_PATH))
    enums_to_build.append(scan_directory_for_names(ANIMAL_ASSETS_PATH))

    # Write the Python File
    print(f"Writing Enums to: {OUTPUT_PATH}...")
    
    with open(OUTPUT_PATH, "w") as f:
        ## Write the header
        f.write("# ==========================================\n")
        f.write("# THIS FILE IS AUTO-GENERATED BY A SCRIPT.\n")
        f.write("# DO NOT EDIT THIS FILE MANUALLY.\n")
        f.write("# Run tools/generate_enums.py to update.\n")
        f.write("# ==========================================\n\n")
        f.write("from enum import Enum\n\n")
        
        for enum_def in enums_to_build:
            write_enum_class(f, enum_def)

    print("Success! generated_enums.py updated perfectly.")

if __name__ == "__main__":
    build_enum_file()